version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: python3 bot.py
  poller:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: python3 poller.py
